unclassified:
  globalLibraries:
    libraries:
    - defaultVersion: "master"
      name: "meetup-jenkins-lib"
      retriever:
        modernSCM:
          scm:
            git:
              remote: "https://github.com/PRODYNA/meetup-jenkins-lib.git"
              traits:
              - "branchDiscoveryTrait"
