apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  demo-jenkins-jenkins-config: "true"
  app: meetup-demo

configMapGenerator:
- name: jenkins-config-as-code
  files:
  - jenkins-config.yaml